In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [3]:
import numpy as np
data = [1,2,3]
arr = np.array(data)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
#파이썬 리스트

data = [1,2,3]

result = []
for i in data:
    result.append(i * 10)
print(result)

[10, 20, 30]


In [5]:
# 넘파이 활용

import numpy as np

arr = np.array([1,2,3])
result = arr * 10
print(result)

[10 20 30]


In [7]:
# 첫 번째 행만 출력

data2d = [
[1,2,3],
[4,5,6],
[7,8,9]
]

print(data2d[0])

[1, 2, 3]


In [9]:
# 콜론(:)을 사용하면 행을 선택하는 것

import numpy as np

data2d = [
[1,2,3],
[4,5,6],
[7,8,9]
]

arr = np.array(data2d)
print(arr[ : , 0])

[1 4 7]


In [11]:
data1 = [1,2,3,4]

arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [15]:
data2 = [
    [1,2],
    [3,4]
]
arr2 = np.array(data2)
print(arr2)
print(type(arr2))
print(type(arr2[0]))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [17]:
# shape은 ndarray의 크기 정보
# ndim은 차원 정보
# dtype은 데이터 타입

print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

(2, 2)
2
int64


In [18]:
# 1차원 데이터는 튜플로 저장됨(그래서 데이터 길이로 표현)

print(arr1.shape)

(4,)


In [19]:
data = [
    [1],
    [2],
    [3],
    [4]
]
c = np.array(data)
print( c.shape )

(4, 1)


In [21]:
# zeros와 ones 함수는 float 타입으로 저장

print(np.zeros(3))
print(np.ones(3))

[0. 0. 0.]
[1. 1. 1.]


In [22]:
# 3행 4열

size = (3, 4)
print(np.zeros(size))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
print( np.zeros((3, 4)) )

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
1: print(np.arange(5))
2: print(np.arange(1, 5))
3: print(np.arange(1, 5, 2))

#= 라인1,2,3이 안돼서 도움을 요청해봤다

SyntaxError: illegal target for annotation (4034498443.py, line 1)

# Assistant
The error occurs because the code has line numbers included in the actual code, which Python interprets as invalid syntax. In Python, you can't have numbers followed by colons at the beginning of lines as they're being interpreted as invalid annotation targets.

Would you like me to provide the corrected code?

In [27]:
# Remove the line numbers (1:, 2:, 3:) from the code
import numpy as np  # First import numpy

print(np.arange(5))
print(np.arange(1, 5))
print(np.arange(1, 5, 2))

[0 1 2 3 4]
[1 2 3 4]
[1 3]


In [28]:
# reshape로 2차원 배열로 변환하기

ndarr1 = np.arange(6)
ndarr2 = ndarr1.reshape(2, 3)
print(ndarr2)

[[0 1 2]
 [3 4 5]]


In [29]:
arr = np.array([1,2,3], dtype=np.uint8)
print(arr.dtype)
print(arr.dtype.kind)
print(arr.dtype.alignment)

uint8
u
1


In [30]:
# astype는 새로운 ndarray 객체 리턴

arr = arr.astype('int8')
print(arr.dtype)

int8


In [32]:
a = np.array([0, 255], dtype=np.uint8)
b = a.astype('int8')
print(a)
print(b)

[  0 255]
[ 0 -1]


In [33]:
# 16비트와 32비트에 나누기 연산 적용하기

a16 = np.array([1,1.333333 ], dtype=np.float16)
a32 = np.array([1,1.333333 ], dtype=np.float32)
print(a16/3)
print(a32/3)

[0.3333 0.4443]
[0.33333334 0.44444433]


In [34]:
# nan은 숫자가 아닌 값 혹은 정의되지 않은 숫자
# inf는 무한대의 숫자

print(np.nan, type(np.nan))
print(np.inf, type(np.inf))
print(-np.inf, type(-np.inf))

nan <class 'float'>
inf <class 'float'>
-inf <class 'float'>


In [35]:
# 수학에서 0으로 나누기는 정의되지 않는 것처럼 경고 발생

arr = np.array([-1, 2, -3])
print(arr/0)

[-inf  inf -inf]


/tmp/ipykernel_128/4227457732.py:2: RuntimeWarning: divide by zero encountered in divide
  print(arr/0)


In [36]:
arr = np.array([-1, 2, -3])
print(arr + np.nan)
print(arr + np.inf)

[nan nan nan]
[inf inf inf]


In [37]:
# 인덱싱

arr = np.arange(4)
print(arr[0])

0


In [39]:
arr = np.arange(4). reshape(2,2)
print(arr[0])

[0 1]


In [41]:
print(arr[0][0])
print(arr[0, 0])

0
0


In [42]:
# timeit: 뒤에 나오는 코드를 1000만 번 반복 실행 후 걸린 시간의 평균 반환

a=np.arange(10000).reshape(100, 100)
%timeit a[0, 50]

134 ns ± 24.7 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [43]:
# 두 번에 걸쳐서 연속 인덱싱할 경우

a=np.arange(10000).reshape(100, 100)
%timeit a[0][50]

214 ns ± 5.26 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [44]:
arr = np.arange(4)
print(arr[:2])

[0 1]


In [45]:
target = [0,2] #가져오려는 데이터의 인덱스 리스트 정의
print(arr[ target ]) #데이터의 위치 정보가 담긴 리스트 사용 후 슬라이싱

[0 2]


In [46]:
print(arr[ [0,2] ])

[0 2]


In [48]:
arr = np.arange(20).reshape(4,5)
print(arr[:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [49]:
result = []
for row in arr:
    row_01 = [ row[0], row[1] ]
    result.append(row_01)

In [50]:
print(arr[:,2])

[ 2  7 12 17]


In [51]:
print(arr[ 1:4, 2:5])
print(arr[ 1:, 2: ])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [53]:
a = np.array( [1,2,3] )
b = np.array( [2,3,4] )
print( a+b )
print( a*b )
print( a%b )

[3 5 7]
[ 2  6 12]
[1 2 3]


In [54]:
print(a+3)

[4 5 6]


In [ ]:
# 브로드캐스팅 = 연산이 ndarray로 확장 적용되는 것
# 조건 1: 뒤축의 길이가 같다
# 조건 2: 비교하는 어느 한 축 길이가 1이다

In [55]:
high = [92700, 92400, 92100, 9430, 92300]
low = [90000, 91100, 91700, 92100, 90900]

arr_high = np.array(high)
arr_low = np.array(low)

arr_diff = arr_high - arr_low
print(arr_diff)

[  2700   1300    400 -82670   1400]


In [57]:
arr_high_x3 = arr_high*3
arr_low_x2 = arr_low*2
print(arr_high_x3 + arr_low_x2)

[458100 459400 459700 212490 458700]


In [58]:
avg = (arr_high_x3) + (arr_low_x2)

In [59]:
data = [
[92700, 92400, 92100, 9430, 92300],
[90000, 91100, 91700, 92100, 90900]
]
arr = np.array(data)

In [60]:
print(arr[0] * 3 + arr[1] * 2)

[458100 459400 459700 212490 458700]


In [62]:
weight = np.array( [3, 2] ).reshape(2,1) #가중치 값 정의 = 2행 1열이 가중치
print((weight * arr).sum(axis=0)) # 두 개의 ndarray를 곱하고 x축을 기준으로 합 계산

[458100 459400 459700 212490 458700]


In [63]:
arr = np.array([10, 20, 30])
print(arr > 10)

[False  True  True]


In [64]:
arr = np.array([10, 20, 30])
cond = [False, True, True]
print(arr[ cond ])

[20 30]


In [66]:
arr = np.array([10, 20, 30])
print(arr[[False, True, True]])

[20 30]


In [67]:
arr = np.array([10, 20, 30])
cond = arr > 10
print(arr[ cond ])

[20 30]


In [68]:
print(arr[ arr > 10 ])

[20 30]


In [69]:
cond.all()
cond.any()

True

In [70]:
arr = np.array([10,20,30])
print(arr[ (arr>10) & (arr<30) ])

[20]


In [72]:
arr = np.array([10,20,30])
cond = arr > 10
arr[cond] = 1
arr[~cond] = 0
print(arr)

[0 1 1]


In [73]:
arr = np.array([10,20,30])
arr = np.where(arr>10, 1, 0)
print(arr)

[0 1 1]


In [74]:
cond = arr > 10
arr[cond] = arr[cond] + 10
arr[~cond] = arr[~cond] - 10

In [75]:
arr = np.where(arr>10, arr+10, arr-10)

In [77]:
lge = np.array([93000, 82400, 81000, 72300])
result = lge[ lge<=85000 ]
print(len(result))

3


In [78]:
arr = np.arange(8).reshape(4, 2)
print(arr.sum())

28


In [79]:
print(arr.sum(axis=0)) # axis=0은 x축 방향으로 데이터의 합 구하기

[12 16]


In [80]:
print(arr.sum(axis=1)) # axis=1은 y축 방향으로 데이터 합 구하기

[ 1  5  9 13]


In [82]:
# randit 함수 = 입력된 범위에서 임의의 정수 반환
np.random.randint(3)

1

In [ ]:
np.random.randit(46, size=5) # 0~45까지의 수를 5개 생성 후 ndarray로 반환
np.random.randit(46, size=(2,5)) # 0~45까지의 수를 2행 5열의 2차원 ndarray로 반환

In [83]:
# linspace 함수 = 첫 번째로 시작하는 값, 두 번째는 종료값, 세 번째는 분할 지점의 수를 입력 받아서 균일하게 분할시키는 함수
x = np.linspace(0, 10, 3)
print(x)

[ 0.  5. 10.]


In [ ]:
# y = x^2
y = x**2

In [84]:
# vstack은 수직방향으로 ndarray를 이어 붙임
# hstack은 수평 방향으로 ndarray를 이어 붙임

a = np.arange(4) # a가 ndarray [0123] 바인딩
b = np.arange(4, 8) # b가 ndarray [4567] 바인딩
c = np.vstack( [a,b]) # 연결할 ndarray를 리스트로 묶은 후 vstack 메서드로 연결
print(c)

[[0 1 2 3]
 [4 5 6 7]]


In [85]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [86]:
from pandas import Series # Series 사용하기 위한 모듈 import

data = [10, 20, 30]
s = Series(data) # 시리즈 객체 생성
print(s)

0    10
1    20
2    30
dtype: int64


In [87]:
from pandas import Series
import numpy as np

data = np.arange(5)
s = Series(data)
print(s)

0    0
1    1
2    2
3    3
4    4
dtype: int64


In [88]:
data = ["시가", "고가"]
s = Series(data)
print(s)

0    시가
1    고가
dtype: object


In [90]:
# object 타입
s = Series(['samsung', 81000])
print(s)

0    samsung
1      81000
dtype: object


In [91]:
from pandas import Series

data = [1000, 2000, 3000]
s = Series(data)
print(s.index)
print(s.index.to_list())

RangeIndex(start=0, stop=3, step=1)
[0, 1, 2]


In [92]:
data = [1000, 2000, 3000]
s = Series(data)
s.index = ["메로나", "구구콘", "하겐다즈"]
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [93]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]

s = Series(data, index)
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [94]:
class Series:
    def__init__(self, data=None, index=None, ....):
pass

SyntaxError: positional argument follows keyword argument (2888815889.py, line 2)

In [95]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]

s = Series(data=data, index=index)

In [96]:
v = [1000, 2000, 3000]
k = ["메로나", "구구콘", "하겐다즈"]
s = Series(data=v, index=k)

In [97]:
s = Series(data, index)
s = Series(data, index=index)
s = Series(data=data, index=index)
s = Series(inex=index, data=data)

TypeError: Series.__init__() got an unexpected keyword argument 'inex'

In [98]:
data = [1000, 2000, 3000]
index = ['메로나', '구구콘', '하겐다즈']
s = Series(data=data, index=index)
s2 = s.reindex(['메로나', '비비빅', '구구콘']) #이렇게 되면 비비빅은 존재하지 않은 결측값으로 처리
print(s2)

메로나    1000.0
비비빅       NaN
구구콘    2000.0
dtype: float64


In [99]:
print(s2.fillna(0))

메로나    1000.0
비비빅       0.0
구구콘    2000.0
dtype: float64


In [101]:
s2 = s.reindex(["메로나", "비비빅", "구구콘"], fill_value=0)

In [102]:
price = [42500, 42550, 41800, 42550, 42650]
date = ["2019-05-31", "2019-05-30", "2019-05-29", "2019-05-28", "2019-05-27"]
s = Series(price, date)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [105]:
data = [
    "2019-05-31" : 42500,
    "2019-05-30" : 42550,
    "2019-05-29" : 41800,
    "2019-05-28" : 42550,
    "2019-05-27" : 42650
]
s = Series(data)

SyntaxError: invalid syntax (3262199564.py, line 2)

In [106]:
print(s.index)
print(s.index.dtype)

Index(['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27'], dtype='object')
object


In [107]:
print(s.values)

[42500 42550 41800 42550 42650]


In [109]:
from pandas import Series

data = [1000, 2000, 3000]
s = Series(data=data)

print(s.iloc[0])
print(s.iloc[1])
print(s.iloc[2])
print(s.iloc[-1])

1000
2000
3000
3000


In [110]:
# 생략
print(s.loc[0])
print(s.loc[1])
print(s.loc[2])
print(s.loc[-1]) #error

1000
2000
3000


KeyError: -1

In [111]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data=data, index=index)

print(s.iloc[0])
print(s.loc['메로나'])

1000
1000


In [112]:
# 생략
print(s['메로나'])
print(s[0])

1000
1000


In [113]:
s1 = Series([10, 20, 30])
s2 = Series([10, 20, 30], index=[1,2,3])
print(s1[0])
print(s2[0]) #인덱스 0은 없어서 에러

10


KeyError: 0

In [114]:
s3 = Series([10, 20, 30], index=['a', 'b', 'c'])
print(s3[0])

10


In [115]:
print(s3.index[0])
print(s3.index[-1])

a
c
